build_two_objects: two_objects launch
build_sun: sun launch
	
two_objects:
	g++ two_objects.cpp -o simulator -lsfml-graphics -lsfml-window -lsfml-system classes.cpp


sun:
	g++ simulate_sun.cpp -o simulator -lsfml-graphics -lsfml-window -lsfml-system classes.cpp


launch:
	./simulator